# Generated by Django 4.2.13 on 2026-04-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings_app', '0001_initial'),
        ('classes', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promotion_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('promoted', 'Promoted'), ('failed', 'Failed'), ('withdrawn', 'Withdrawn')], default='promoted', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('from_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='settings_app.academicyear')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='classes.class')),
                ('from_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='classes.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='students.studentprofile')),
                ('to_academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='settings_app.academicyear')),
                ('to_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='classes.class')),
                ('to_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='classes.section')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
