# Generated by Django 4.2.13 on 2026-04-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('classes', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='class_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.class'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='classes.section'),
        ),
        migrations.AddField(
            model_name='studentattendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.studentprofile'),
        ),
        migrations.AddField(
            model_name='staffattendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='staff.staffprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='studentattendance',
            unique_together={('student', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='staffattendance',
            unique_together={('staff', 'date')},
        ),
    ]
