# Generated by Django 4.2.13 on 2026-04-22 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='applied_for_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions', to='classes.class'),
        ),
    ]
